service: aws-python-openweather
frameworkVersion: '3'

useDotenv: true

plugins: ${file(./serverless/config/plugins.yml)}
provider: ${file(./serverless/config/provider.yml)}
custom: ${file(./serverless/config/custom.yml)}
  

functions:
  - ${file(./serverless/ForecastWeatherByCity.yml)}
  - ${file(./serverless/GetToken.yml)}
  - ${file(./serverless/Users.yml)}
  - ${file(./serverless/Resources.yml)}
